[project]
name = "collective_accounting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "funcy>=2.0",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
